### ISSUE TITLE
警報の設定画面のバグ

### ISSUE THREAD

**Issue by miumiu1031** [yosukeh/try1#133]
【バグ１】
「警報の設定画面」で「警告」を出す症状と記載されてる。
「警報」に統一すべき

【バグ２】
警報の設定を行う際、「何が？」が行動の場合でも「どんなときに？」が症状の表現（悪い、とても悪いとか）になっている。行動の表現（多い、とても多い）等に変わるようにすべき

**Comment by yosukeh** [comment]
そもそも画面、操作しずらくない?

**Comment by yosukeh** [comment]
あと、警告で、文言を出せてもいい気がした。。。
