### ISSUE TITLE
症状/行動追加直後のHomeで、追加されたアイテムを分かりやすく表示

### ISSUE THREAD

**Issue by yosukeh** [yosukeh/try1#14]
エフェクトをかけるとか、Boldにするとか。

「お、増えた！！やった！！」　的な感じで。

**Comment by miumiu1031** [comment]
記録画面に同じ症状を持つ人の統計グラフを出すようにして、追加が完了すると統計グラフがすぐに見えるようにする案

**Comment by yosukeh** [comment]
赤まるで「New」って出すだけ。
画面リロードしたら消える。
情報は、追加時のURLに入れる。
