### ISSUE TITLE
Day１の文言確認

### ISSUE THREAD

**Issue by miumiu1031** [yosukeh/try1#141]

**Comment by miumiu1031** [comment]
【新規ID登録画面】
　・「利用キーワードをご存じない方は利用できません」は不要
　
　・Beda版のため・・・以降の文章
　「Beta版のため、不具合が発生したり、予告なく機能が変更されたりする場合があります。」
　にする。パスワードとかの文言はそのままで。

【メニュー】
・「気になる症状の設定」
　→特に改善したい症状の設定
・気になる症状の設定画面
　→特に改善したい症状を設定しましょう。先頭に表示したり、警報を設定できるようになります。

・症状/行動の表示設定
　→症状や行動の表示/非表示設定

**Comment by yosukeh** [comment]
すべて反映。
