### ISSUE TITLE
警報登録機能の作成

### ISSUE THREAD

**Issue by miumiu1031** [yosukeh/try1#21]
警報登録機能を作成する。
仕様は、Condition仕様_0.001.02のP43~46、67,18
p42のように、警告を出す

★削除ができん。

**Comment by yosukeh** [comment]
【完了】作業順序①　登録編：
・UI大枠
　・report_sp.phpに、基本的なDIVを配置する
　・警告登録ページの大枠作る
　　・入力の基本的なDIVを配置する
・ロジック作成
　・DB設計する
　・ダミーデータ登録する
　→ｙ１の体調(220)用。
　・渡すJsonの形式を固めて、RestAPIのphpのJavaDocに書く
　・UIぐちゃぐちゃでいいので、設定をUIで入力できるようにする
　　・登録済み警告の設定を表示できるようにする。
　　・登録した警告に、条件を追加できるできるようにする。　　
　　　・UIを作る
　　　・追加する処理を作る（OK後のページ遷移あり）　
　　　　 ・JSONで送るかな。で、パース後、全部Intのことを確認してDB格納。PHPから受け取ったJSONを編集して、それを返す形。
　　　　　　　　(セキュリティ的に今のところ問題指摘はないとのこと。Evalしてないし。)
http://isket.jp/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0/json%E5%BD%A2%E5%BC%8F%E3%82%92php%E3%81%A7%E3%83%91%E3%83%BC%E3%82%B9%E3%81%99%E3%82%8B/
　　　　　　・送付機能を作る
    　　　　・受信機能を作る 
　　　　　　　・送られてきたデータを全部追加。 
　　　　　　　・いままでのワーニングリストを消す
　　　　　　・パースし、DataBaseに書き込む。
    ・警告条件（大項目）を追加できるようにする。こ
　　　・UIを作る
　　　・追加する処理を作る（OK後のページ遷移あり）　
　　・回避条件（大項目）を追加できるようにする。　　　
　　　・UIを作る
　　　・追加する処理を作る（OK後のページ遷移あり）　
　　・登録済み警告がない場合、追加する枠を表示できるようにする
　・何が　が症状と行動が切り替わった時に「どんなとき」を切り替える
　・発生条件の1条件の中のAND条件追加機能
　・発生条件の条件追加機能
　・回避条件の条件追加機能
　・occure_or_avoid　を廃止
  ・大項目を削除できるようにする
　・isCollapsedを追加。　
　・各大黒目に、タイトルバーを出すようにする
●UI改善
　・JSオブジェクトを使うようにする
　　　・既存のCollapibleをCollapsibleとCollapsibleListに分ける。
　　　・今回は、単にCollapsibleを使うだけにする。-> やめて独自実装で進める。
 　・各大項目をFOLDできるようにする 
・警告を出す症状を切り替えたときに、その症状ように切り替わる
 ・Item_IDを　item_record_id に変更。

**Comment by yosukeh** [comment]
作業順序②　警告表示編：

●警告表示　　　
　・警告を出すかの判定を行う（これはサーバサイド。PHPかな。）
　　・判定SQL文の作成（マッチした発生条件と回避条件を出す）
　　　・そのユーザの登録警告一覧取得
　　　・各Detail条件の日付条件（朝5時に切り替わる方式）にマッチした物だけ表示
　　　　　・今日、入力のあった症状だけ表示（ためし）
　　　　　　・入力のあった症状RecordIdを取得
　　　　　　・その入力のあった症状RecordIDのWarningConditionだけ表示
　　　　　・各Detail条件の日付条件（0時に切り替わる方式）にマッチした物だけ表示
               ・当日のもの
　　　　　　　・１日前のもの（それぞれ別にINNERJOINしていけばできそう。）　
　　　　　　　・2－４日前のもの（それぞれ別にINNERJOINしていけばできそう。）
　　　　　　・やっぱり、演算で求めよう。
                       select CASE WHEN ( NOW() % 1000000 ) < 50000 THEN 1 ELSE 2 END
   　　　　　　　　　　　　　で、5時よりあとなら、も見れる。（Selectはいらない）
　　　　　　　　　　　　　　　あとは、SQL文内で変数を使いたい。。。
　　　　　　　　　　　　　　

　　　・各Detail条件のどんなときに　の条件にマッチしたものだけ表示
       ・行動にも対応　
      　・重複があったら、より悪いほうだけ取得。
　　　・マッチした条件グループだけ表示　　
　　　　　・重複を除去して、Warning_IDごとにカウント
　　　　　・重複を除去して、Warning_IDごとに、本来のCondition数をカウント（Deleteされているのは除去）
　　　　　・カウントが一致するものに、Wanringが成立したものに、フラグをつける
　　　　・Symptomが悪化するものにフラグを付ける
　　　　・SQL文で帰るもののHelpを関数のHelpに書く

   　・controller- forecast - warning.php　
　　　　・DBから警告情報を取得する（warning.php内）
       　　・JSONで返せるようにする
　　　　　・一旦表示する
　　　　　　　・警告の出た症状
　　　　　　　・マッチした警告の内容。
       　　　　　・IDでの表示　
　　　　　　　　・症状/行動名での表示。「やや悪い以上」なども書く。
　　　　　　　・回避方法
　　　　　　　・回避できている場合は、回避方法
   　 ・API開通
　　・表示する
　　　　　★symptom_warning_idは、固定にしなければならない。発生済み警告Tableに入れるために、「発生条件ID」が必要。
        ・symptom_warning_idの固定化
　　　　　　　　・Javascript側：詳細Conditionsも、Delete時にDB側はIsDeletedをつけるだけにする。で、isDeletedのものも送る。ｉｓＤｅｌｅｔｅｄで、ＩＤのないものは送らない。　　　
　　　　　　　　・受信PHP側：symptom_warning_idやsymptom_warning_codition_idがある場合はUPDATEを使う。それ以外はINSERT。
　　　　　・発生したワーニングを、表示。
　　　　　　・文言は、仕様書にあったかな。
　　　　　・

**Comment by yosukeh** [comment]
Between  Now() + cond_when*100000000  and   now() + cond_when \* 10000000+100000000
でいけるんじゃない。

**Comment by yosukeh** [comment]
ようやくできた。表示仕様はまだ微妙だな。
あと、Indicatorを下げる条件も。
