### ISSUE TITLE
上部のConditionのタグをスクロール時に消す

### ISSUE THREAD

**Issue by miumiu1031** [yosukeh/try1#22]

**Comment by yosukeh** [comment]
入力ボタン部分のdivの高さを固定にして、その中をスクロールするようにする。
上の部分と入力ボタン部分を合わせると、ヘッダの上の部分がはみ出る大きさにする。

**Comment by yosukeh** [comment]
やってみたが、Androidだと、1回目のロードとそれ以外で、window.innerHeightの値がばらけるため、難しい。
