### ISSUE TITLE
「限定表示」機能

### ISSUE THREAD

**Issue by yosukeh** [yosukeh/try1#55]
名前を「●×▲」とか「_=--」とかに変えるでもいいし
　ユースケース：
　　・人に説明する
　　・医者に見せる

**Comment by yosukeh** [comment]
まず仕様がほしい

**Comment by miumiu1031** [comment]
画面の左上にアイコン作成。
アイコンを押すと、他人に見せるモードになる。
モードは、自分専用と、他人に見せる用の2種類

**Comment by yosukeh** [comment]
・非表示モードに入る処理
　・モード切替ボタンを作る。
　・どれを表示するかのフィルタ画面を作る
　・OKしたら、クッキーに非表示のIDを書き込む。
　・リロード
　・PHP側で、非表示のIDは、リターンしないようにする。
・非表示モード解除
　・モード切替ボタン
　・
