### ISSUE TITLE
【コメント求む】Notificationの文言考える。　　これ結構大事。

### ISSUE THREAD

**Issue by yosukeh** [yosukeh/try1#94]
種類：
　　①　Notificaitonの瞬間　
　　　　　最長：未計測
　　②　Notificaitonのタイトル　
　　　　最長：◆◆◆◆◆◆◆◆◆◆◆◆◆
　　③　Notificaitonの詳細
　　　　最長：◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆

今：
①　　conditions
②下記をのどれかをランダム
　　　・体調いかがですか？
　　　・気になる症状はどうですか？
③
　　・記録と改善で、良い状態の日を増やそう

（本来、症状の良い時と悪い時で分けるべき。）

**Comment by miumiu1031** [comment]
①　　conditions　（よい）
②下記をのどれかをランダム
　　　・体調いかがですか？　（よい）
 　　  ・気になる症状はどうですか？
③
　　・記録を続けて体調を管理しましょう。
　　・記録を続けて症状の改善目指しましょう
　　・記録を続けると改善のヒントが見つかるかもしれません。

（本来、症状の良い時と悪い時で分けるべき。）

**Comment by miumiu1031** [comment]
③
　・記録をつけて、改善のヒントを見つけましょう
　・記録をつけて、改善を目指しましょう。
　・記録をつけて、体調の管理をしましょう。（Day1 ではこれが無難か？）

**Comment by yosukeh** [comment]
3     気になる症状を記録してコントロールしよう 

はどう?
ログイン画面と統一する

**Comment by yosukeh** [comment]
下記に確定。

②
　体調いかがですか？　
③
　気になる症状を記録してコントロールしよう
